### ISSUE TITLE
Ctrl-W does not work if data view has focus.  Ctrl-F4 works well in this case but does not work if the TreeView has the focus.

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#355]

**Comment by jipclaassens** [comment]
Erik: ctr f4
Maarten ctr w

**Comment by MaartenHilferink** [comment]
Both Ctrl-W and Ctrl-F4 are sent to a DataView's parent hWND, being the HWND of a QDmsViewArea object.



![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/75e207e1-f8df-4db9-8df3-8c77568a3d42)

**Comment by MaartenHilferink** [comment]
Fixed Ctrl+W by replacing it as Ctrl+F4 as follows:


![Image](https://github.com/ObjectVision/GeoDMS/assets/2284361/d69eb8b1-ed29-43fb-8015-f80ffd8555fb)

Note that Ctrl+Alt+W and Ctrl+Shift+W still work as Tile and Cascade without adaptation.

**Comment by MaartenHilferink** [comment]
In windows menu, "Close Window (Ctrl+W)" should be added.

**Comment by jipclaassens** [comment]
This is still an issue: 
- New view is opened, and then ctrl+W doesn't work
- Click in the new view, and then ctrl+W doesn't work
- Click in detail page, and then ctrl+W does work
- Click in tree view, and then ctrl+W does work

**Comment by eoudejans** [comment]
> This is still an issue:
> 
> * New view is opened, and then ctrl+W doesn't work
> * Click in the new view, and then ctrl+W doesn't work
> * Click in detail page, and then ctrl+W does work
> * Click in tree view, and then ctrl+W does work

The above scenarios seem to work at my side, could you reconfirm that in the latest GeoDMS version this is still an issue?

**Comment by jipclaassens** [comment]
It would be preferable when you close a tab that you do not switch to the first (most left) still open tab but to the last opened (far right).

**Comment by jipclaassens** [comment]
- if statistics view is opened ctr+w does not work
- if table view is opened, than switched to other tab and then back to table view tab. Ctrl+W also doesn't work
